### ISSUE TITLE
Intuitive and fun UI. Clear title and description for the extension.

### ISSUE THREAD

**Issue by ArcInnov** [ArcInnov/AI-powered-Chrome-extension-inspired-by-Emma-Watson#4]
Intuitive and fun UI. Clear title and description for the extension.

- On clicking extension icon show a popup that has Emma Watson's photo with a magic wand
- Show some fun magic spell under the photo 
- Add button with clear call to action
- On button click output github user id in an alert ... In a future issue this will be replaced by call to Google's AI face recognition API
- Write up a helpful and clear title and description for the extension (We got to look good for the Chrome Web Store) 😇 😉 

TODO .... Replace this with a UI sample from EKAGI

**Comment by ekagi** [comment]
@ArcInnov Aha, love that you aiming for a Chrome Web Store release now 😃 
Here is a "fun" UI sample that I put togehter based on you issue description

![image](https://user-images.githubusercontent.com/108222223/179674834-e3f0ab7b-c885-4c9b-8749-4134a9a85099.png)
